from enum import StrEnum


class EventType(StrEnum):
    DIVIDEND = "DIVIDEND"
    JCP = "JCP"
    BONUS_SHARES = "BONUS_SHARES"
    STOCK_SPLIT = "STOCK_SPLIT"
    REVERSE_SPLIT = "REVERSE_SPLIT"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class FieldStatus(StrEnum):
    EXTRACTED = "EXTRACTED"
    REFERENCE_ENRICHED = "REFERENCE_ENRICHED"
    DERIVED = "DERIVED"
    NOT_DISCLOSED = "NOT_DISCLOSED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    AMBIGUOUS = "AMBIGUOUS"
    CONFLICT = "CONFLICT"
    UNREADABLE = "UNREADABLE"
    UNKNOWN = "UNKNOWN"


class Origin(StrEnum):
    DOCUMENT = "DOCUMENT"
    REFERENCE = "REFERENCE"
    DERIVED = "DERIVED"
    UNKNOWN = "UNKNOWN"


class ConfidenceLevel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ExtractionMethod(StrEnum):
    NATIVE_TEXT = "NATIVE_TEXT"
    OCR = "OCR"


class ValidationStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_EVALUATED = "NOT_EVALUATED"


class ProcessingStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    PENDING_INFORMATION = "PENDING_INFORMATION"
    FAILED = "FAILED"


class ExtractionStrategy(StrEnum):
    PYTHON = "PYTHON"
    BASIC_LLM = "BASIC_LLM"
    STRONG_LLM = "STRONG_LLM"


class ExtractionAttemptOutcome(StrEnum):
    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT = "INSUFFICIENT"
    ERROR = "ERROR"


class ExceptionCategory(StrEnum):
    BUSINESS_EXCEPTION = "BUSINESS_EXCEPTION"
    VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION"
    REVIEW_EXCEPTION = "REVIEW_EXCEPTION"
    TECHNICAL_ERROR = "TECHNICAL_ERROR"


class RatioKind(StrEnum):
    NEW_PER_EXISTING = "NEW_PER_EXISTING"
    RESULTING_PER_EXISTING = "RESULTING_PER_EXISTING"


class TaxTreatment(StrEnum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    TAX_EXEMPT = "TAX_EXEMPT"
    TAX_RULE_UNIFORM = "TAX_RULE_UNIFORM"
    TAX_DEPENDS_ON_BENEFICIARY = "TAX_DEPENDS_ON_BENEFICIARY"
    UNKNOWN = "UNKNOWN"
